entitiesConfiguration:
    namespace: App\Doctrine\Entity\
    entityPath: app/src/Doctrine/Entity

entities:
    example:
        table: example
        classname: Example

    user:
        table: user
        classname: User

    account:
        table: account
        classname: Account
