entitiesConfiguration:
    namespace: SlimMicroService\Entity\
    entityPath: app/src/Entity
    actionsSupported:
        create: read: \SlimMicroService\Action\ActionCreate
        read: \SlimMicroService\Action\ActionRead

entities:
    example:
        adapter: doctrine
        table: example
        classname: Example
