entitiesConfiguration:
    namespace: SlimMicroService\Entity\
    entityPath: app/src/Entity
    actionsSupported:
        create: \SlimMicroService\Action\ActionCreate
        read: \SlimMicroService\Action\ActionRead
        update: \SlimMicroService\Action\ActionUpdate
        delete: \SlimMicroService\Action\ActionDelete

entities:
    example:
        adapter: doctrine
        table: example
        classname: Example
