entitiesConfiguration:
    namespace: SlimMicroService\Entity\Doctrine\
    entityPath: src/app/Entity/Doctrine/
    actionsSupported:
        create: \SlimMicroService\Action\Create
        read: \SlimMicroService\Action\Read
        update: \SlimMicroService\Action\Update
        delete: \SlimMicroService\Action\Delete

entities:
    example:
        adapter: doctrine
        table: example
        classname: Example
        extends: \SlimMicroService\Entity\DoctrineDefault
