entitiesConfiguration:
    namespace: SlimMicroService\Entity\
    entityPath: src/app/Entity
    actionsSupported:
        create: \SlimMicroService\Action\Create
        read: \SlimMicroService\Action\Read
        update: \SlimMicroService\Action\Update
        delete: \SlimMicroService\Action\Delete

entities:
    example:
        adapter: doctrine
        table: example
        classname: Example
